// Russian Baggage cards. Owner: ru-content-world (reports/i18n-design.md §12).
//
// The same 109 ids as ../en/baggage.js. Only this file changes: a missing English key or a function that needs another
// param goes to i18n-content (content code and ../en/*.js) as a note, never into ../en/*.js or the code.
//
// Binding: the glossary and style guide in reports/i18n-design.md §10 (SPEC §11 X5.6). In short: ты to the player;
// player names never declined; no gendered form about a card's owner (a card can be revealed before Biology and swapped
// by Body Swap); quotes «…», the em dash with spaces, the decimal comma, ё everywhere; Russian words for acronyms (only
// °C, 3D, USB and × may stay Latin). Every card is a nominative noun phrase: the log prints it after a colon.
//
// Positional template syntax (design §6.3). The English entry's placeholders, counted left to right from 0, are the
// params; here every one is an {n:a-b} number:
//   {0}               prints param 0
//   {0|год|года|лет}  the plural word for numeric param 0, one|few|many, right after the printed number
// Units that do not decline (кг, Вт, %) take no plural word; every other counted word does.
export const COMPLETE = true;

export default {
  'tt-pistol-with-rounds': 'Пистолет ТТ и {0} {0|патрон|патрона|патронов}',
  'hunting-rifle-with-cartridges': 'Охотничье ружьё и {0} {0|патрон|патрона|патронов}',
  'crossbow-with-bolts': 'Арбалет и {0} {0|болт|болта|болтов}',
  'bag-of-vegetable-seeds-kg': 'Мешок семян овощей ({0} кг)',
  'sack-of-seed-potatoes-kg': 'Мешок семенной картошки ({0} кг)',
  'first-aid-kit': 'Аптечка',
  'surgical-instrument-set': 'Набор хирургических инструментов',
  'antibiotics-courses': 'Антибиотики ({0} {0|курс|курса|курсов})',
  'insulin-doses': 'Инсулин ({0} {0|доза|дозы|доз})',
  'iodine-pills-against-radiation': 'Таблетки йода от радиации ({0} {0|штука|штуки|штук})',
  'a-years-supply-of-vitamins': 'Годовой запас витаминов',
  'box-of-condoms': 'Коробка презервативов ({0} {0|штука|штуки|штук})',
  'pregnancy-tests': 'Тесты на беременность ({0} {0|штука|штуки|штук})',
  'canned-food-cans': 'Консервы ({0} {0|банка|банки|банок})',
  'hand-crank-radio': 'Радиоприёмник с ручной динамо-машиной',
  'axe': 'Топор',
  'portable-water-filter': 'Походный фильтр для воды',
  'chainsaw-no-fuel': 'Бензопила (без бензина)',
  'folding-solar-panel-w': 'Складная солнечная панель ({0} Вт)',
  'tent-for-people': 'Палатка на {0} {0|человека|человека|человек}',
  'sleeping-bag': 'Спальный мешок',
  'fishing-rod-and-a-tackle-box': 'Удочка и коробка со снастями',
  'laptop-with-an-offline-copy-of': 'Ноутбук с офлайн-копией Википедии',
  'encyclopedia-of-medicinal-plants': 'Энциклопедия лекарственных растений',
  'holy-book': 'Священная книга',
  'chess-set': 'Шахматы',
  'deck-of-playing-cards': 'Колода игральных карт',
  'vodka-liters': 'Водка ({0} {0|литр|литра|литров})',
  'cat-in-a-carrier': 'Кот в переноске',
  'german-shepherd': 'Немецкая овчарка',
  'a-hen-and-a-rooster-in-a-crate': 'Курица и петух в ящике',
  'pregnant-goat': 'Беременная коза',
  'hamster': 'Хомяк',
  'parrot-that-swears-in-languages': 'Попугай, который ругается на {0} {0|языке|языках|языках}',
  'beehive-with-bees': 'Улей (с пчёлами)',
  'gas-mask-with-spare-filters': 'Противогаз и {0} {0|фильтр|фильтра|фильтров} про запас',
  'hazmat-suit': 'Костюм химзащиты',
  'geiger-counter': 'Счётчик Гейгера',
  'night-vision-goggles': 'Очки ночного видения',
  'binoculars': 'Бинокль',
  'compass-and-paper-maps': 'Компас и бумажные карты',
  'satellite-phone-battery': 'Спутниковый телефон (заряд {0}%)',
  'gold-bars-kg': 'Золотые слитки ({0} кг)',
  'suitcase-with-a-million-dollars': 'Чемодан с миллионом долларов наличными',
  'usb-stick-holding-bitcoin': 'Флешка, на которой {0} {0|биткоин|биткоина|биткоинов}',
  'vinyl-record-collection': 'Коллекция виниловых пластинок',
  'karaoke-machine': 'Караоке-система',
  'wedding-dress': 'Свадебное платье',
  'tuxedo': 'Смокинг',
  'toilet-paper-rolls': 'Туалетная бумага ({0} {0|рулон|рулона|рулонов})',
  'lighter-and-gas-refills': 'Зажигалка и {0} {0|баллончик|баллончика|баллончиков} газа',
  'matches-boxes': 'Спички ({0} {0|коробок|коробка|коробков})',
  'swiss-army-knife': 'Швейцарский армейский нож',
  'crowbar': 'Монтировка',
  'duct-tape-rolls': 'Армированный скотч ({0} {0|рулон|рулона|рулонов})',
  'toolbox': 'Ящик с инструментами',
  'portable-welding-machine': 'Переносной сварочный аппарат',
  'diesel-generator-with-liters-of': 'Дизельный генератор и {0} {0|литр|литра|литров} топлива',
  'bicycle': 'Велосипед',
  'inflatable-kayak': 'Надувной каяк',
  'sewing-kit': 'Швейный набор',
  'knitting-needles-and-balls-of': 'Спицы и {0} {0|клубок|клубка|клубков} пряжи',
  'book-home-childbirth-for': 'Книга «Роды на дому для начинающих»',
  'childrens-picture-books': 'Детские книжки с картинками',
  'board-game-with-half-the-pieces': 'Настольная игра, в которой не хватает половины фишек',
  'harmonica': 'Губная гармошка',
  'violin': 'Скрипка',
  'accordion': 'Аккордеон',
  'drum-kit': 'Барабанная установка',
  'paints-and-canvases': 'Краски и холсты',
  'instant-camera-shots-left': 'Полароид (плёнки ещё на {0} {0|снимок|снимка|снимков})',
  'rubber-duck': 'Резиновая уточка',
  'garden-gnome': 'Садовый гном',
  'jar-of-sourdough-starter': 'Банка закваски для хлеба',
  'salt-kg': 'Соль ({0} кг)',
  'sugar-kg': 'Сахар ({0} кг)',
  'coffee-beans-kg': 'Кофе в зёрнах ({0} кг)',
  'cigarettes-packs': 'Сигареты ({0} {0|пачка|пачки|пачек})',
  'chocolate-bars': 'Шоколад ({0} {0|плитка|плитки|плиток})',
  'jar-of-honey-kg': 'Банка мёда ({0} кг)',
  'cast-iron-cooking-pot': 'Чугунный котелок',
  'microscope': 'Микроскоп',
  'childrens-chemistry-set': 'Набор «Юный химик»',
  'flare-gun-with-flares': 'Ракетница и {0} {0|ракета|ракеты|ракет}',
  'handcuffs-without-a-key': 'Наручники без ключа',
  'metal-detector': 'Металлоискатель',
  'snorkel-and-flippers': 'Трубка и ласты',
  'hammock': 'Гамак',
  'diary-of-the-bunkers-previous': 'Дневник прежнего владельца бункера',
  'urn-with-grandmas-ashes': 'Урна с прахом бабушки',
  'stuffed-owl': 'Чучело совы',
  'tattoo-machine': 'Тату-машинка',
  'hair-clippers': 'Машинка для стрижки волос',
  'makeup-kit': 'Набор косметики',
  'unchecked-lottery-ticket': 'Непроверенный лотерейный билет',
  'treasure-map': 'Карта сокровищ',
  'locked-box-that-must-never-be': 'Запертый ящик, который ни в коем случае нельзя открывать',
  'crate-of-beer-bottles': 'Ящик пива ({0} {0|бутылка|бутылки|бутылок})',
  'rice-kg': 'Рис ({0} кг)',
  'dynamite-sticks': 'Динамит ({0} {0|шашка|шашки|шашек})',
  'camera-drone': 'Дрон с камерой',
  'pair-of-walkie-talkies': 'Пара раций',
  'rope-m': 'Верёвка ({0} {0|метр|метра|метров})',
  'water-barrel-liters': 'Бочка воды ({0} {0|литр|литра|литров})',
  'grow-lamp': 'Фитолампа',
  'car-battery': 'Автомобильный аккумулятор',
  'megaphone': 'Мегафон',
  'teddy-bear': 'Плюшевый мишка',
  'samurai-sword-decorative': 'Самурайский меч (декоративный)',
};
