// Russian Health cards. Owner: ru-content-body (reports/i18n-design.md §12).
//
// The same 79 ids as ../en/health.js. Binding: the glossary and style guide in reports/i18n-design.md §10 (SPEC §11
// X5.6): no gendered form about the card's owner (a card can be revealed before Biology and swapped by Body Swap), so
// nouns and the present tense, never the past tense, short adjectives or participles about the owner; «…», —, –,
// the decimal comma, ё; no Latin letters (Hepatitis C is «гепатит С» with a Cyrillic С; HIV «ВИЧ»).
//
// Positional template syntax (design §6.3). The English entry's placeholders, counted left to right from 0, are the
// params ({n:a-b} a number, {yrs:a-b} a number of years, {sev} a severity index 0..2, {x|y|z} an option index):
//   {0}               prints param 0: the number for {n:a-b}; «3 года» for {yrs:a-b} (./mods.js yrs); the default
//                     severity phrase for {sev} (./mods.js sev: «лёгкая форма», «средней тяжести», «тяжёлая форма»).
//   {0|неделю|недели|недель}   the plural word for numeric param 0, one|few|many, right after the printed number.
//   {1:а|б|в}         the option for an {x|y|z} param (as many options as English has) or a {sev} param (exactly 3).
// A numeral after «на», «через», «ещё» in a time phrase is accusative: «ещё 2 недели», «на 5 лет».
export const COMPLETE = true;

export default {
  'perfectly-healthy': 'Идеальное здоровье',
  'perfectly-healthy-athletic-build': 'Идеальное здоровье (спортивное телосложение)',
  'perfectly-healthy-just-passed-a': 'Идеальное здоровье (только что с полного медосмотра)',
  'perfectly-healthy-iron-immune': 'Идеальное здоровье (железный иммунитет)',
  'perfectly-healthy-blood-type-o': 'Идеальное здоровье (первая отрицательная группа крови — универсальный донор)',
  'perfectly-healthy-has-never-been': 'Идеальное здоровье (у врача — ни разу в жизни)',
  'perfectly-healthy-fertility-test': 'Идеальное здоровье (тест на фертильность: отлично)',
  'perfectly-healthy-runs-a': 'Идеальное здоровье (каждый год бегает марафон)',
  'perfectly-healthy-perfect': 'Идеальное здоровье (стопроцентное зрение)',
  'perfectly-healthy-except-for-a': 'Идеальное здоровье (если не считать тяги к сладкому)',
  'perfectly-healthy-and-never': 'Идеальное здоровье (и не даёт никому об этом забыть)',
  'asthma': 'Астма ({0})',
  'type-1-diabetes-needs-insulin': 'Диабет 1 типа (инсулин каждый день)',
  'type-2-diabetes': 'Диабет 2 типа ({0})',
  'infertility': 'Бесплодие ({0:лечится препаратами|не лечится})',
  'hemophilia': 'Гемофилия ({0})',
  'epilepsy-seizures': 'Эпилепсия (приступы {0:каждую неделю|примерно раз в месяц|примерно раз в год})',
  'chronic-migraine': 'Хроническая мигрень ({0})',
  'near-sightedness-diopters-no': 'Близорукость (−{0}\u00a0{0|диоптрия|диоптрии|диоптрий}, запасных очков нет)',
  'color-blindness': 'Дальтонизм',
  'deaf-in-the-ear': 'Глухота на {0:левое|правое} ухо',
  'blind-in-one-eye': 'Слепота на один глаз',
  'missing-hand-uses-a-prosthesis': 'Нет {0:левой|правой} кисти (носит протез)',
  'paraplegia-uses-a-wheelchair': 'Параплегия (передвигается в инвалидной коляске)',
  'obesity-class': 'Ожирение (степень {0})',
  'anorexia': 'Анорексия ({0})',
  'allergy-to': 'Аллергия на {0:арахис|пыль|кошек|пенициллин|укусы пчёл|плесень|глютен} ({1})',
  'lactose-intolerance': 'Непереносимость лактозы',
  'celiac-disease': 'Целиакия',
  'high-blood-pressure': 'Гипертония ({0})',
  'heart-arrhythmia': 'Аритмия сердца ({0})',
  'survived-a-heart-attack-ago': 'Инфаркт {0} назад',
  'cancer-stage': 'Рак (стадия {0})',
  'cancer-in-remission': 'Рак в ремиссии (уже {0})',
  'early-stage-alzheimers-disease': 'Болезнь Альцгеймера, ранняя стадия',
  'parkinsons-disease': 'Болезнь Паркинсона ({0})',
  'multiple-sclerosis': 'Рассеянный склероз ({0})',
  'schizophrenia-stable-on': 'Шизофрения (на препаратах — стойкая ремиссия)',
  'bipolar-disorder': 'Биполярное расстройство ({0})',
  'clinical-depression': 'Клиническая депрессия ({0})',
  'ptsd': 'Посттравматическое расстройство ({0})',
  'obsessive-compulsive-disorder': 'Обсессивно-компульсивное расстройство ({0})',
  'panic-disorder': 'Паническое расстройство ({0})',
  'chronic-insomnia': 'Хроническая бессонница',
  'narcolepsy-falls-asleep-mid': 'Нарколепсия (засыпает на полуслове)',
  'sleepwalking': 'Лунатизм ({0})',
  'snores-so-loudly-it-carries': 'Храпит так, что слышно через стены',
  'chronic-back-pain': 'Хроническая боль в спине ({0:терпимая|ощутимая|изматывающая})',
  'rheumatoid-arthritis': 'Ревматоидный артрит ({0})',
  'kidney-stones': 'Камни в почках',
  'only-one-kidney': 'Всего одна почка',
  'stomach-ulcer': 'Язва желудка ({0})',
  'tuberculosis-active-contagious': 'Туберкулёз (открытая, заразная форма)',
  'hepatitis-c-treatable': 'Гепатит С (лечится)',
  'hiv-positive-on-therapy': 'ВИЧ (на терапии, вирусная нагрузка не определяется)',
  'albinism-skin-burns-after': 'Альбинизм (кожа обгорает на солнце за считаные минуты)',
  'anemia': 'Анемия ({0})',
  'radiation-sickness': 'Лучевая болезнь ({0})',
  'alcohol-addiction': 'Алкогольная зависимость ({0})',
  'nicotine-addiction-a-day': 'Никотиновая зависимость ({0:пачка|две пачки|три пачки} в день)',
  'gambling-addiction': 'Игровая зависимость',
  'hypochondria-convinced-they-are': 'Ипохондрия (твёрдая уверенность, что дни сочтены)',
  'broken-leg-in-a-cast-for-more': 'Перелом ноги (в гипсе ещё {0}\u00a0{0|неделю|недели|недель})',
  'stutter': 'Заикание ({0})',
  'hiccups-that-have-lasted-weeks': 'Икота, которая не проходит уже {0}\u00a0{0|неделю|недели|недель}',
  'common-cold-sneezes-on-everyone': 'Простуда (чихает на всех)',
  'head-lice': 'Вши',
  'chronic-fatigue-syndrome': 'Синдром хронической усталости',
  'amnesia-remembers-nothing-before': 'Амнезия (не помнит ничего до прошлого года)',
  'scoliosis': 'Сколиоз ({0})',
  'tinnitus-a-constant-ringing-in': 'Тиннитус (постоянный звон в ушах)',
  'sickle-cell-disease': 'Серповидноклеточная анемия',
  'immune-to-most-common-viruses-a': 'Иммунитет к большинству обычных вирусов (редкая мутация)',
  'carrier-of-an-unknown-virus-no': 'Носитель неизвестного вируса (симптомов нет)',
  'terminal-illness-doctors-gave': 'Неизлечимая болезнь (врачи дают {0}\u00a0{0|месяц|месяца|месяцев})',
  'pacemaker-battery-good-for-more': 'Кардиостимулятор (батарейки хватит ещё на {0})',
  'hearing-aid-the-batteries-are': 'Слуховой аппарат (батарейки садятся)',
  'gout': 'Подагра ({0})',
  'dental-abscess-constant': 'Зубной абсцесс (зуб ноет не переставая)',
};
