// Russian Hobby cards. Owner: ru-content-body (reports/i18n-design.md §12).
//
// The same 74 ids as ../en/hobbies.js. Binding: the glossary and style guide in reports/i18n-design.md §10 (SPEC §11
// X5.6). A hobby is the name of an activity (a noun phrase), so it says nothing about its owner's gender; a remark in
// brackets uses the present tense («смотрит, но не готовит»). Only 3D may stay Latin.
//
// Positional template syntax (design §6.3): {0} prints the English entry's first placeholder (here a number), and
// {0|штука|штуки|штук} is its plural word, one|few|many, right after the printed number.
// The duration modifier («5 лет», «с детства») is added from ./mods.js (hobby, hobbyWrap); an entry with its own "(…)"
// in English gets none.
export const COMPLETE = true;

export default {
  'fishing': 'Рыбалка',
  'hunting': 'Охота',
  'gardening': 'Садоводство',
  'beekeeping': 'Пчеловодство',
  'mushroom-picking': 'Сбор грибов',
  'chess': 'Шахматы',
  'poker': 'Покер',
  'knitting': 'Вязание',
  'sewing': 'Шитьё',
  'guitar': 'Гитара',
  'piano': 'Фортепиано',
  'singing-in-a-choir': 'Пение в хоре',
  'karaoke': 'Караоке',
  'yoga': 'Йога',
  'boxing': 'Бокс',
  'rock-climbing': 'Скалолазание',
  'hiking': 'Пешие походы',
  'camping': 'Походы с палаткой',
  'parkour': 'Паркур',
  'archery': 'Стрельба из лука',
  'fencing': 'Фехтование',
  'swimming': 'Плавание',
  'scuba-diving': 'Дайвинг',
  'skydiving': 'Прыжки с парашютом',
  'woodcarving': 'Резьба по дереву',
  'pottery': 'Гончарное дело',
  'oil-painting': 'Живопись маслом',
  'photography': 'Фотография',
  'writing-poetry': 'Сочинение стихов',
  'reading-science-fiction': 'Чтение фантастики',
  'cosplay': 'Косплей',
  'video-games': 'Видеоигры',
  'tabletop-role-playing-games': 'Настольные ролевые игры',
  'stargazing': 'Наблюдение за звёздами',
  'birdwatching': 'Наблюдение за птицами',
  'brewing-beer-at-home': 'Домашнее пивоварение',
  'making-wine-at-home': 'Домашнее виноделие',
  'baking-bread': 'Выпечка хлеба',
  'pickling-and-canning': 'Соленья и закатки',
  'foraging-for-wild-plants': 'Сбор дикорастущих трав и кореньев',
  'ham-radio': 'Любительская радиосвязь',
  'soldering-electronics': 'Пайка электроники',
  '3d-printing': '3D-печать',
  'drone-racing': 'Гонки дронов',
  'model-railways': 'Железнодорожный моделизм',
  'stamp-collecting': 'Коллекционирование марок',
  'coin-collecting': 'Коллекционирование монет',
  'taxidermy': 'Таксидермия',
  'card-tricks': 'Карточные фокусы',
  'juggling': 'Жонглирование',
  'ballroom-dancing': 'Бальные танцы',
  'breakdancing': 'Брейк-данс',
  'researching-conspiracy-theories': 'Изучение теорий заговора',
  'prepping-for-the-apocalypse': 'Подготовка к апокалипсису',
  'geocaching': 'Геокэшинг',
  'orienteering': 'Спортивное ориентирование',
  'motorcycle-repair': 'Ремонт мотоциклов',
  'sailing': 'Парусный спорт',
  'horse-riding': 'Верховая езда',
  'keeping-aquarium-fish': 'Аквариумные рыбки',
  'calligraphy': 'Каллиграфия',
  'origami': 'Оригами',
  'crossword-puzzles': 'Кроссворды',
  'meditation': 'Медитация',
  'reading-tarot-cards': 'Гадание на картах таро',
  'astrology': 'Астрология',
  'sport-lockpicking': 'Спортивное вскрытие замков',
  'knife-throwing': 'Метание ножей',
  'blacksmithing': 'Кузнечное дело',
  'soap-making': 'Мыловарение',
  'family-tree-research': 'Составление родословной',
  'learning-a-made-up-language-from': 'Изучение выдуманного языка из сериала',
  'collecting-bottle-caps-of-them': 'Коллекционирование пробок от бутылок (уже {0}\u00a0{0|штука|штуки|штук})',
  'watching-cooking-shows-never': 'Кулинарные шоу (смотрит, но никогда не готовит)',
};
