// Russian Phobia cards. Owner: ru-content-body (reports/i18n-design.md §12).
//
// The same 58 ids as ../en/phobias.js (the id is the English name before the colon). Binding: the glossary and style
// guide in reports/i18n-design.md §10 (SPEC §11 X5.6). Shape «<Название>: боязнь <чего>» (genitive, or an infinitive
// for an action). No gendered form about the card's owner: «боязнь погребения заживо», not «…быть похороненным».
// No placeholders in this file; the intensity («в тяжёлой форме», «до панических атак») is added from ./mods.js
// (phobiaIntensity, phobiaWrap).
export const COMPLETE = true;

export default {
  'claustrophobia': 'Клаустрофобия: боязнь замкнутых пространств',
  'nyctophobia': 'Никтофобия: боязнь темноты',
  'arachnophobia': 'Арахнофобия: боязнь пауков',
  'hemophobia': 'Гемофобия: боязнь крови',
  'acrophobia': 'Акрофобия: боязнь высоты',
  'agoraphobia': 'Агорафобия: боязнь открытых пространств и толпы',
  'aquaphobia': 'Аквафобия: боязнь воды',
  'cynophobia': 'Кинофобия: боязнь собак',
  'ailurophobia': 'Айлурофобия: боязнь кошек',
  'ophidiophobia': 'Офидиофобия: боязнь змей',
  'musophobia': 'Мусофобия: боязнь мышей и крыс',
  'entomophobia': 'Энтомофобия: боязнь насекомых',
  'mysophobia': 'Мизофобия: боязнь микробов и грязи',
  'trypanophobia': 'Трипанофобия: боязнь игл и уколов',
  'iatrophobia': 'Ятрофобия: боязнь врачей',
  'thanatophobia': 'Танатофобия: боязнь смерти',
  'autophobia': 'Аутофобия: боязнь одиночества',
  'social-phobia': 'Социофобия: боязнь чужого осуждения',
  'glossophobia': 'Глоссофобия: боязнь публичных выступлений',
  'aerophobia': 'Аэрофобия: боязнь полётов',
  'astraphobia': 'Астрафобия: боязнь грома и молнии',
  'pyrophobia': 'Пирофобия: боязнь огня',
  'emetophobia': 'Эметофобия: боязнь рвоты',
  'coulrophobia': 'Коулрофобия: боязнь клоунов',
  'trypophobia': 'Трипофобия: боязнь скоплений мелких отверстий',
  'nomophobia': 'Номофобия: боязнь остаться без телефона',
  'gerascophobia': 'Гераскофобия: боязнь старости',
  'pediophobia': 'Педиофобия: боязнь кукол',
  'somniphobia': 'Сомнифобия: боязнь заснуть',
  'phasmophobia': 'Фазмофобия: боязнь призраков',
  'technophobia': 'Технофобия: боязнь техники',
  'radiophobia': 'Радиофобия: боязнь радиации',
  'ornithophobia': 'Орнитофобия: боязнь птиц',
  'lachanophobia': 'Лаханофобия: боязнь овощей',
  'mycophobia': 'Микофобия: боязнь грибов',
  'anthropophobia': 'Антропофобия: боязнь людей',
  'philophobia': 'Филофобия: боязнь влюбиться',
  'gamophobia': 'Гамофобия: боязнь обязательств и брака',
  'tokophobia': 'Токофобия: боязнь беременности и родов',
  'pogonophobia': 'Погонофобия: боязнь бород',
  'hippopotomonstrosesquippedaliophobia': 'Гиппопотомонстросесквиппедалиофобия: боязнь длинных слов',
  'ergophobia': 'Эргофобия: боязнь работы',
  'cibophobia': 'Цибофобия: боязнь еды',
  'chionophobia': 'Хионофобия: боязнь снега',
  'heliophobia': 'Гелиофобия: боязнь солнечного света',
  'nosocomephobia': 'Нозокомефобия: боязнь больниц',
  'paraskevidekatriaphobia': 'Параскаведекатриафобия: боязнь пятницы, 13-го',
  'omphalophobia': 'Омфалофобия: боязнь пупков',
  'bathophobia': 'Батофобия: боязнь глубины',
  'kenophobia': 'Кенофобия: боязнь пустых комнат',
  'atychiphobia': 'Атихифобия: боязнь неудачи',
  'decidophobia': 'Децидофобия: боязнь принимать решения',
  'gerontophobia': 'Геронтофобия: боязнь стариков',
  'selenophobia': 'Селенофобия: боязнь луны',
  'xanthophobia': 'Ксантофобия: боязнь жёлтого цвета',
  'chronophobia': 'Хронофобия: боязнь течения времени',
  'mechanophobia': 'Механофобия: боязнь машин и механизмов',
  'taphophobia': 'Тафофобия: боязнь погребения заживо',
};
