// English Baggage cards: 109 entries.
//
// Today's English strings, verbatim, keyed by stable ids (reports/i18n-design.md §6.1–§6.2). The ids never change
// once published (B1): a reworded card keeps its id. The key order is the deck order, so reordering or inserting
// entries changes what a seed deals (the golden test in test/i18n-golden-content.test.js says so on purpose).
//
// Placeholders are drawn left to right when the card is dealt:
//   {n:a-b}    a whole number from a to b
//   {yrs:a-b}  "N years" ("1 year"), N from a to b
//   {sev}      a severity word from ./mods.js (mild / moderate / severe)
//   {x|y|z}    one of the options
// ../ru/ refers to them by position: {0} is the first placeholder, {1} the second (design §6.3).
export default {
  'tt-pistol-with-rounds': 'TT pistol with {n:2-16} rounds',
  'hunting-rifle-with-cartridges': 'Hunting rifle with {n:5-40} cartridges',
  'crossbow-with-bolts': 'Crossbow with {n:3-20} bolts',
  'bag-of-vegetable-seeds-kg': 'Bag of vegetable seeds ({n:1-5} kg)',
  'sack-of-seed-potatoes-kg': 'Sack of seed potatoes ({n:10-30} kg)',
  'first-aid-kit': 'First aid kit',
  'surgical-instrument-set': 'Surgical instrument set',
  'antibiotics-courses': 'Antibiotics ({n:2-10} courses)',
  'insulin-doses': 'Insulin ({n:10-90} doses)',
  'iodine-pills-against-radiation': 'Iodine pills against radiation ({n:20-200})',
  'a-years-supply-of-vitamins': "A year's supply of vitamins",
  'box-of-condoms': 'Box of condoms ({n:10-144})',
  'pregnancy-tests': 'Pregnancy tests ({n:3-20})',
  'canned-food-cans': 'Canned food ({n:10-60} cans)',
  'hand-crank-radio': 'Hand-crank radio',
  'axe': 'Axe',
  'portable-water-filter': 'Portable water filter',
  'chainsaw-no-fuel': 'Chainsaw (no fuel)',
  'folding-solar-panel-w': 'Folding solar panel ({n:50-400} W)',
  'tent-for-people': 'Tent for {n:2-8} people',
  'sleeping-bag': 'Sleeping bag',
  'fishing-rod-and-a-tackle-box': 'Fishing rod and a tackle box',
  'laptop-with-an-offline-copy-of': 'Laptop with an offline copy of Wikipedia',
  'encyclopedia-of-medicinal-plants': 'Encyclopedia of medicinal plants',
  'holy-book': 'Holy book',
  'chess-set': 'Chess set',
  'deck-of-playing-cards': 'Deck of playing cards',
  'vodka-liters': 'Vodka ({n:2-10} liters)',
  'cat-in-a-carrier': 'Cat in a carrier',
  'german-shepherd': 'German shepherd',
  'a-hen-and-a-rooster-in-a-crate': 'A hen and a rooster in a crate',
  'pregnant-goat': 'Pregnant goat',
  'hamster': 'Hamster',
  'parrot-that-swears-in-languages': 'Parrot that swears in {n:2-4} languages',
  'beehive-with-bees': 'Beehive (with bees)',
  'gas-mask-with-spare-filters': 'Gas mask with {n:2-6} spare filters',
  'hazmat-suit': 'Hazmat suit',
  'geiger-counter': 'Geiger counter',
  'night-vision-goggles': 'Night-vision goggles',
  'binoculars': 'Binoculars',
  'compass-and-paper-maps': 'Compass and paper maps',
  'satellite-phone-battery': 'Satellite phone (battery {n:5-60}%)',
  'gold-bars-kg': 'Gold bars ({n:1-12} kg)',
  'suitcase-with-a-million-dollars': 'Suitcase with a million dollars in cash',
  'usb-stick-holding-bitcoin': 'USB stick holding {n:2-50} bitcoin',
  'vinyl-record-collection': 'Vinyl record collection',
  'karaoke-machine': 'Karaoke machine',
  'wedding-dress': 'Wedding dress',
  'tuxedo': 'Tuxedo',
  'toilet-paper-rolls': 'Toilet paper ({n:4-48} rolls)',
  'lighter-and-gas-refills': 'Lighter and {n:2-10} gas refills',
  'matches-boxes': 'Matches ({n:5-50} boxes)',
  'swiss-army-knife': 'Swiss army knife',
  'crowbar': 'Crowbar',
  'duct-tape-rolls': 'Duct tape ({n:2-12} rolls)',
  'toolbox': 'Toolbox',
  'portable-welding-machine': 'Portable welding machine',
  'diesel-generator-with-liters-of': 'Diesel generator with {n:10-100} liters of fuel',
  'bicycle': 'Bicycle',
  'inflatable-kayak': 'Inflatable kayak',
  'sewing-kit': 'Sewing kit',
  'knitting-needles-and-balls-of': 'Knitting needles and {n:2-15} balls of yarn',
  'book-home-childbirth-for': "Book: 'Home Childbirth for Beginners'",
  'childrens-picture-books': "Children's picture books",
  'board-game-with-half-the-pieces': 'Board game with half the pieces missing',
  'harmonica': 'Harmonica',
  'violin': 'Violin',
  'accordion': 'Accordion',
  'drum-kit': 'Drum kit',
  'paints-and-canvases': 'Paints and canvases',
  'instant-camera-shots-left': 'Instant camera ({n:5-40} shots left)',
  'rubber-duck': 'Rubber duck',
  'garden-gnome': 'Garden gnome',
  'jar-of-sourdough-starter': 'Jar of sourdough starter',
  'salt-kg': 'Salt ({n:2-20} kg)',
  'sugar-kg': 'Sugar ({n:2-20} kg)',
  'coffee-beans-kg': 'Coffee beans ({n:1-10} kg)',
  'cigarettes-packs': 'Cigarettes ({n:5-50} packs)',
  'chocolate-bars': 'Chocolate bars ({n:10-100})',
  'jar-of-honey-kg': 'Jar of honey ({n:1-5} kg)',
  'cast-iron-cooking-pot': 'Cast-iron cooking pot',
  'microscope': 'Microscope',
  'childrens-chemistry-set': "Children's chemistry set",
  'flare-gun-with-flares': 'Flare gun with {n:2-6} flares',
  'handcuffs-without-a-key': 'Handcuffs without a key',
  'metal-detector': 'Metal detector',
  'snorkel-and-flippers': 'Snorkel and flippers',
  'hammock': 'Hammock',
  'diary-of-the-bunkers-previous': "Diary of the bunker's previous owner",
  'urn-with-grandmas-ashes': "Urn with grandma's ashes",
  'stuffed-owl': 'Stuffed owl',
  'tattoo-machine': 'Tattoo machine',
  'hair-clippers': 'Hair clippers',
  'makeup-kit': 'Makeup kit',
  'unchecked-lottery-ticket': 'Unchecked lottery ticket',
  'treasure-map': 'Treasure map',
  'locked-box-that-must-never-be': 'Locked box that must never be opened',
  'crate-of-beer-bottles': 'Crate of beer ({n:12-48} bottles)',
  'rice-kg': 'Rice ({n:5-50} kg)',
  'dynamite-sticks': 'Dynamite ({n:2-10} sticks)',
  'camera-drone': 'Camera drone',
  'pair-of-walkie-talkies': 'Pair of walkie-talkies',
  'rope-m': 'Rope ({n:10-100} m)',
  'water-barrel-liters': 'Water barrel ({n:50-200} liters)',
  'grow-lamp': 'Grow lamp',
  'car-battery': 'Car battery',
  'megaphone': 'Megaphone',
  'teddy-bear': 'Teddy bear',
  'samurai-sword-decorative': 'Samurai sword (decorative)',
};
