// English Health cards: 79 entries (about 15% are "Perfectly healthy" in some form).
//
// Today's English strings, verbatim, keyed by stable ids (reports/i18n-design.md §6.1–§6.2). The ids never change
// once published (B1): a reworded card keeps its id. The key order is the deck order, so reordering or inserting
// entries changes what a seed deals (the golden test in test/i18n-golden-content.test.js says so on purpose).
//
// Placeholders are drawn left to right when the card is dealt:
//   {n:a-b}    a whole number from a to b
//   {yrs:a-b}  "N years" ("1 year"), N from a to b
//   {sev}      a severity word from ./mods.js (mild / moderate / severe)
//   {x|y|z}    one of the options
// ../ru/ refers to them by position: {0} is the first placeholder, {1} the second (design §6.3).
export default {
  'perfectly-healthy': 'Perfectly healthy',
  'perfectly-healthy-athletic-build': 'Perfectly healthy (athletic build)',
  'perfectly-healthy-just-passed-a': 'Perfectly healthy (just passed a full medical check-up)',
  'perfectly-healthy-iron-immune': 'Perfectly healthy (iron immune system)',
  'perfectly-healthy-blood-type-o': 'Perfectly healthy (blood type O-negative, a universal donor)',
  'perfectly-healthy-has-never-been': 'Perfectly healthy (has never been to a doctor)',
  'perfectly-healthy-fertility-test': 'Perfectly healthy (fertility test: excellent)',
  'perfectly-healthy-runs-a': 'Perfectly healthy (runs a marathon every year)',
  'perfectly-healthy-perfect': 'Perfectly healthy (perfect eyesight)',
  'perfectly-healthy-except-for-a': 'Perfectly healthy (except for a sweet tooth)',
  'perfectly-healthy-and-never': 'Perfectly healthy (and never stops mentioning it)',
  'asthma': 'Asthma ({sev})',
  'type-1-diabetes-needs-insulin': 'Type 1 diabetes (needs insulin every day)',
  'type-2-diabetes': 'Type 2 diabetes ({sev})',
  'infertility': 'Infertility ({treatable with medication|untreatable})',
  'hemophilia': 'Hemophilia ({sev})',
  'epilepsy-seizures': 'Epilepsy (seizures {every week|about once a month|about once a year})',
  'chronic-migraine': 'Chronic migraine ({sev})',
  'near-sightedness-diopters-no': 'Near-sightedness (-{n:2-9} diopters, no spare glasses)',
  'color-blindness': 'Color blindness',
  'deaf-in-the-ear': 'Deaf in the {left|right} ear',
  'blind-in-one-eye': 'Blind in one eye',
  'missing-hand-uses-a-prosthesis': 'Missing {left|right} hand (uses a prosthesis)',
  'paraplegia-uses-a-wheelchair': 'Paraplegia (uses a wheelchair)',
  'obesity-class': 'Obesity (class {n:1-3})',
  'anorexia': 'Anorexia ({sev})',
  'allergy-to': 'Allergy to {peanuts|dust|cats|penicillin|bee stings|mold|gluten} ({sev})',
  'lactose-intolerance': 'Lactose intolerance',
  'celiac-disease': 'Celiac disease',
  'high-blood-pressure': 'High blood pressure ({sev})',
  'heart-arrhythmia': 'Heart arrhythmia ({sev})',
  'survived-a-heart-attack-ago': 'Survived a heart attack {yrs:1-9} ago',
  'cancer-stage': 'Cancer (stage {n:1-4})',
  'cancer-in-remission': 'Cancer in remission ({yrs:1-10})',
  'early-stage-alzheimers-disease': "Early-stage Alzheimer's disease",
  'parkinsons-disease': "Parkinson's disease ({sev})",
  'multiple-sclerosis': 'Multiple sclerosis ({sev})',
  'schizophrenia-stable-on': 'Schizophrenia (stable on medication)',
  'bipolar-disorder': 'Bipolar disorder ({sev})',
  'clinical-depression': 'Clinical depression ({sev})',
  'ptsd': 'PTSD ({sev})',
  'obsessive-compulsive-disorder': 'Obsessive-compulsive disorder ({sev})',
  'panic-disorder': 'Panic disorder ({sev})',
  'chronic-insomnia': 'Chronic insomnia',
  'narcolepsy-falls-asleep-mid': 'Narcolepsy (falls asleep mid-sentence)',
  'sleepwalking': 'Sleepwalking ({sev})',
  'snores-so-loudly-it-carries': 'Snores so loudly it carries through walls',
  'chronic-back-pain': 'Chronic back pain ({sev})',
  'rheumatoid-arthritis': 'Rheumatoid arthritis ({sev})',
  'kidney-stones': 'Kidney stones',
  'only-one-kidney': 'Only one kidney',
  'stomach-ulcer': 'Stomach ulcer ({sev})',
  'tuberculosis-active-contagious': 'Tuberculosis (active, contagious)',
  'hepatitis-c-treatable': 'Hepatitis C (treatable)',
  'hiv-positive-on-therapy': 'HIV-positive (on therapy, undetectable)',
  'albinism-skin-burns-after': 'Albinism (skin burns after minutes in the sun)',
  'anemia': 'Anemia ({sev})',
  'radiation-sickness': 'Radiation sickness ({sev})',
  'alcohol-addiction': 'Alcohol addiction ({sev})',
  'nicotine-addiction-a-day': 'Nicotine addiction ({a pack|two packs|three packs} a day)',
  'gambling-addiction': 'Gambling addiction',
  'hypochondria-convinced-they-are': 'Hypochondria (convinced they are dying)',
  'broken-leg-in-a-cast-for-more': 'Broken leg (in a cast for {n:2-6} more weeks)',
  'stutter': 'Stutter ({sev})',
  'hiccups-that-have-lasted-weeks': 'Hiccups that have lasted {n:2-9} weeks',
  'common-cold-sneezes-on-everyone': 'Common cold (sneezes on everyone)',
  'head-lice': 'Head lice',
  'chronic-fatigue-syndrome': 'Chronic fatigue syndrome',
  'amnesia-remembers-nothing-before': 'Amnesia (remembers nothing before last year)',
  'scoliosis': 'Scoliosis ({sev})',
  'tinnitus-a-constant-ringing-in': 'Tinnitus (a constant ringing in the ears)',
  'sickle-cell-disease': 'Sickle cell disease',
  'immune-to-most-common-viruses-a': 'Immune to most common viruses (a rare mutation)',
  'carrier-of-an-unknown-virus-no': 'Carrier of an unknown virus (no symptoms)',
  'terminal-illness-doctors-gave': 'Terminal illness (doctors gave {n:2-12} months)',
  'pacemaker-battery-good-for-more': 'Pacemaker (battery good for {yrs:1-8} more)',
  'hearing-aid-the-batteries-are': 'Hearing aid (the batteries are running out)',
  'gout': 'Gout ({sev})',
  'dental-abscess-constant': 'Dental abscess (constant toothache)',
};
