// English Hobby cards: 74 entries.
//
// Today's English strings, verbatim, keyed by stable ids (reports/i18n-design.md §6.1–§6.2). The ids never change
// once published (B1): a reworded card keeps its id. The key order is the deck order, so reordering or inserting
// entries changes what a seed deals (the golden test in test/i18n-golden-content.test.js says so on purpose).
//
// Placeholders are drawn left to right when the card is dealt:
//   {n:a-b}    a whole number from a to b
//   {yrs:a-b}  "N years" ("1 year"), N from a to b
//   {sev}      a severity word from ./mods.js (mild / moderate / severe)
//   {x|y|z}    one of the options
// ../ru/ refers to them by position: {0} is the first placeholder, {1} the second (design §6.3).
// A Hobby without its own "(...)" gets a duration modifier from ./mods.js when dealt.
export default {
  'fishing': 'Fishing',
  'hunting': 'Hunting',
  'gardening': 'Gardening',
  'beekeeping': 'Beekeeping',
  'mushroom-picking': 'Mushroom picking',
  'chess': 'Chess',
  'poker': 'Poker',
  'knitting': 'Knitting',
  'sewing': 'Sewing',
  'guitar': 'Guitar',
  'piano': 'Piano',
  'singing-in-a-choir': 'Singing in a choir',
  'karaoke': 'Karaoke',
  'yoga': 'Yoga',
  'boxing': 'Boxing',
  'rock-climbing': 'Rock climbing',
  'hiking': 'Hiking',
  'camping': 'Camping',
  'parkour': 'Parkour',
  'archery': 'Archery',
  'fencing': 'Fencing',
  'swimming': 'Swimming',
  'scuba-diving': 'Scuba diving',
  'skydiving': 'Skydiving',
  'woodcarving': 'Woodcarving',
  'pottery': 'Pottery',
  'oil-painting': 'Oil painting',
  'photography': 'Photography',
  'writing-poetry': 'Writing poetry',
  'reading-science-fiction': 'Reading science fiction',
  'cosplay': 'Cosplay',
  'video-games': 'Video games',
  'tabletop-role-playing-games': 'Tabletop role-playing games',
  'stargazing': 'Stargazing',
  'birdwatching': 'Birdwatching',
  'brewing-beer-at-home': 'Brewing beer at home',
  'making-wine-at-home': 'Making wine at home',
  'baking-bread': 'Baking bread',
  'pickling-and-canning': 'Pickling and canning',
  'foraging-for-wild-plants': 'Foraging for wild plants',
  'ham-radio': 'Ham radio',
  'soldering-electronics': 'Soldering electronics',
  '3d-printing': '3D printing',
  'drone-racing': 'Drone racing',
  'model-railways': 'Model railways',
  'stamp-collecting': 'Stamp collecting',
  'coin-collecting': 'Coin collecting',
  'taxidermy': 'Taxidermy',
  'card-tricks': 'Card tricks',
  'juggling': 'Juggling',
  'ballroom-dancing': 'Ballroom dancing',
  'breakdancing': 'Breakdancing',
  'researching-conspiracy-theories': 'Researching conspiracy theories',
  'prepping-for-the-apocalypse': 'Prepping for the apocalypse',
  'geocaching': 'Geocaching',
  'orienteering': 'Orienteering',
  'motorcycle-repair': 'Motorcycle repair',
  'sailing': 'Sailing',
  'horse-riding': 'Horse riding',
  'keeping-aquarium-fish': 'Keeping aquarium fish',
  'calligraphy': 'Calligraphy',
  'origami': 'Origami',
  'crossword-puzzles': 'Crossword puzzles',
  'meditation': 'Meditation',
  'reading-tarot-cards': 'Reading tarot cards',
  'astrology': 'Astrology',
  'sport-lockpicking': 'Sport lockpicking',
  'knife-throwing': 'Knife throwing',
  'blacksmithing': 'Blacksmithing',
  'soap-making': 'Soap making',
  'family-tree-research': 'Family tree research',
  'learning-a-made-up-language-from': 'Learning a made-up language from a TV show',
  'collecting-bottle-caps-of-them': 'Collecting bottle caps ({n:200-3000} of them)',
  'watching-cooking-shows-never': 'Watching cooking shows (never cooks)',
};
