// English Profession cards: 147 entries.
//
// Today's English strings, verbatim, keyed by stable ids (reports/i18n-design.md §6.1–§6.2). The ids never change
// once published (B1): a reworded card keeps its id. The key order is the deck order, so reordering or inserting
// entries changes what a seed deals (the golden test in test/i18n-golden-content.test.js says so on purpose).
//
// Placeholders are drawn left to right when the card is dealt:
//   {n:a-b}    a whole number from a to b
//   {yrs:a-b}  "N years" ("1 year"), N from a to b
//   {sev}      a severity word from ./mods.js (mild / moderate / severe)
//   {x|y|z}    one of the options
// ../ru/ refers to them by position: {0} is the first placeholder, {1} the second (design §6.3).
// A Profession without its own "(...)" gets an experience modifier from ./mods.js when dealt.
export default {
  // medicine
  'surgeon': 'Surgeon',
  'general-practitioner': 'General practitioner',
  'paramedic': 'Paramedic',
  'nurse': 'Nurse',
  'midwife': 'Midwife',
  'dentist': 'Dentist',
  'pediatrician': 'Pediatrician',
  'psychiatrist': 'Psychiatrist',
  'anesthesiologist': 'Anesthesiologist',
  'pharmacist': 'Pharmacist',
  'veterinarian': 'Veterinarian',
  'epidemiologist': 'Epidemiologist',
  'virologist': 'Virologist',
  'plastic-surgeon': 'Plastic surgeon',
  'forensic-pathologist': 'Forensic pathologist',
  'massage-therapist': 'Massage therapist',
  'psychologist': 'Psychologist',
  // food
  'farmer': 'Farmer',
  'agronomist': 'Agronomist',
  'beekeeper': 'Beekeeper',
  'fisherman': 'Fisherman',
  'hunter': 'Hunter',
  'butcher': 'Butcher',
  'chef': 'Chef',
  'pastry-chef': 'Pastry chef',
  'baker': 'Baker',
  'brewer': 'Brewer',
  'sommelier': 'Sommelier',
  'fast-food-cook': 'Fast-food cook',
  'food-critic': 'Food critic',
  'chocolate-factory-taste-tester': 'Chocolate factory taste-tester',
  // trades
  'electrician': 'Electrician',
  'plumber': 'Plumber',
  'welder': 'Welder',
  'carpenter': 'Carpenter',
  'car-mechanic': 'Car mechanic',
  'locksmith': 'Locksmith',
  'bricklayer': 'Bricklayer',
  'blacksmith': 'Blacksmith',
  'tailor': 'Tailor',
  'shoemaker': 'Shoemaker',
  'ventilation-engineer': 'Ventilation engineer',
  'elevator-repair-technician': 'Elevator repair technician',
  'sewer-maintenance-worker': 'Sewer maintenance worker',
  'pest-control-specialist': 'Pest control specialist',
  // science and engineering
  'civil-engineer': 'Civil engineer',
  'mining-engineer': 'Mining engineer',
  'nuclear-physicist': 'Nuclear physicist',
  'chemist': 'Chemist',
  'microbiologist': 'Microbiologist',
  'botanist': 'Botanist',
  'geologist': 'Geologist',
  'meteorologist': 'Meteorologist',
  'astronomer': 'Astronomer',
  'hydrologist': 'Hydrologist',
  'software-developer': 'Software developer',
  'robotics-engineer': 'Robotics engineer',
  'radio-engineer': 'Radio engineer',
  'network-administrator': 'Network administrator',
  'mathematician': 'Mathematician',
  'architect': 'Architect',
  'nuclear-power-plant-operator': 'Nuclear power plant operator',
  'water-treatment-operator': 'Water treatment operator',
  'geneticist': 'Geneticist',
  // security and rescue
  'infantry-soldier': 'Infantry soldier',
  'army-sapper': 'Army sapper',
  'firefighter': 'Firefighter',
  'police-officer': 'Police officer',
  'security-guard': 'Security guard',
  'bodyguard': 'Bodyguard',
  'special-forces-operative': 'Special forces operative',
  'lifeguard': 'Lifeguard',
  'mountain-rescuer': 'Mountain rescuer',
  'prison-guard': 'Prison guard',
  'private-detective': 'Private detective',
  // transport
  'airline-pilot': 'Airline pilot',
  'truck-driver': 'Truck driver',
  'train-driver': 'Train driver',
  'ships-captain': "Ship's captain",
  'submarine-sailor': 'Submarine sailor',
  'taxi-driver': 'Taxi driver',
  'courier': 'Courier',
  'astronaut': 'Astronaut',
  'air-traffic-controller': 'Air traffic controller',
  'ice-cream-truck-driver': 'Ice cream truck driver',
  // education and humanities
  'primary-school-teacher': 'Primary school teacher',
  'kindergarten-teacher': 'Kindergarten teacher',
  'philosophy-lecturer': 'Philosophy lecturer',
  'historian': 'Historian',
  'librarian': 'Librarian',
  'archaeologist': 'Archaeologist',
  'linguist': 'Linguist',
  'translator': 'Translator',
  'journalist': 'Journalist',
  'nanny': 'Nanny',
  'social-worker': 'Social worker',
  // business and law
  'lawyer': 'Lawyer',
  'judge': 'Judge',
  'accountant': 'Accountant',
  'bank-manager': 'Bank manager',
  'tax-inspector': 'Tax inspector',
  'real-estate-agent': 'Real estate agent',
  'stockbroker': 'Stockbroker',
  'crypto-trader': 'Crypto trader',
  'car-salesman': 'Car salesman',
  'marketing-manager': 'Marketing manager',
  'hr-manager': 'HR manager',
  'insurance-agent': 'Insurance agent',
  'city-councillor': 'City councillor',
  'diplomat': 'Diplomat',
  // arts, sports and entertainment
  'actor': 'Actor',
  'opera-singer': 'Opera singer',
  'stand-up-comedian': 'Stand-up comedian',
  'clown': 'Clown',
  'stage-magician': 'Stage magician',
  'circus-acrobat': 'Circus acrobat',
  'tattoo-artist': 'Tattoo artist',
  'hairdresser': 'Hairdresser',
  'fashion-designer': 'Fashion designer',
  'florist': 'Florist',
  'sculptor': 'Sculptor',
  'photographer': 'Photographer',
  'film-director': 'Film director',
  'dj': 'DJ',
  'street-musician': 'Street musician',
  'influencer': 'Influencer',
  'professional-gamer': 'Professional gamer',
  'wedding-planner': 'Wedding planner',
  'fitness-trainer': 'Fitness trainer',
  'football-player': 'Football player',
  'professional-chess-player': 'Professional chess player',
  'stuntman': 'Stuntman',
  'fashion-model': 'Fashion model',
  'tour-guide': 'Tour guide',
  // everything else
  'priest': 'Priest',
  'undertaker': 'Undertaker',
  'fortune-teller': 'Fortune teller',
  'zookeeper': 'Zookeeper',
  'dog-trainer': 'Dog trainer',
  'forest-ranger': 'Forest ranger',
  'janitor': 'Janitor',
  'barista': 'Barista',
  'life-coach': 'Life coach',
  'lighthouse-keeper': 'Lighthouse keeper',
  'postman': 'Postman',
  'unemployed-years-without-a-job': 'Unemployed ({n:2-12} years without a job)',
  'homemaker-raised-children': 'Homemaker (raised {n:2-6} children)',
};
