// English Extra skill cards: 80 entries.
//
// Today's English strings, verbatim, keyed by stable ids (reports/i18n-design.md §6.1–§6.2). The ids never change
// once published (B1): a reworded card keeps its id. The key order is the deck order, so reordering or inserting
// entries changes what a seed deals (the golden test in test/i18n-golden-content.test.js says so on purpose).
//
// Placeholders are drawn left to right when the card is dealt:
//   {n:a-b}    a whole number from a to b
//   {yrs:a-b}  "N years" ("1 year"), N from a to b
//   {sev}      a severity word from ./mods.js (mild / moderate / severe)
//   {x|y|z}    one of the options
// ../ru/ refers to them by position: {0} is the first placeholder, {1} the second (design §6.3).
export default {
  'speaks-languages': 'Speaks {n:3-7} languages',
  'knows-first-aid': 'Knows first aid',
  'has-delivered-a-baby-in-a-taxi': 'Has delivered a baby (in a taxi)',
  'knows-sign-language': 'Knows sign language',
  'former-prisoner-years-for': 'Former prisoner ({n:2-15} years for {fraud|robbery|tax evasion|smuggling|something they refuse to talk about})',
  'can-pick-any-lock-in-under-a': 'Can pick any lock in under a minute',
  'black-belt-in': 'Black belt in {judo|karate|taekwondo}',
  'can-repair-any-engine': 'Can repair any engine',
  'knows-which-wild-plants-are': 'Knows which wild plants are edible',
  'can-start-a-fire-without-matches': 'Can start a fire without matches',
  'photographic-memory': 'Photographic memory',
  'former-olympic': 'Former Olympic {swimmer|rower|biathlete|weightlifter}',
  'can-hypnotize-people-sometimes': 'Can hypnotize people (sometimes)',
  'can-build-a-wind-turbine-from': 'Can build a wind turbine from scrap',
  'can-stitch-wounds': 'Can stitch wounds',
  'plays-any-instrument-by-ear': 'Plays any instrument by ear',
  'knows-morse-code': 'Knows Morse code',
  'can-drive-anything-with-wheels': 'Can drive anything with wheels or tracks',
  'can-distill-alcohol-from-almost': 'Can distill alcohol from almost anything',
  'can-cook-a-decent-meal-from': 'Can cook a decent meal from three ingredients',
  'survived-a-plane-crash': 'Survived a plane crash',
  'knows-how-to-purify-water': 'Knows how to purify water',
  'can-make-soap-and-candles': 'Can make soap and candles',
  'knows-the-engineer-who-built': 'Knows the engineer who built this bunker',
  'knows-where-an-abandoned-army': 'Knows where an abandoned army warehouse is',
  'can-tell-when-someone-is-lying': 'Can tell when someone is lying (usually)',
  'can-sleep-anywhere-anytime': 'Can sleep anywhere, anytime',
  'can-go-without-food-for-days': 'Can go without food for {n:5-10} days',
  'perfect-pitch': 'Perfect pitch',
  'cheats-at-cards-and-never-gets': 'Cheats at cards and never gets caught',
  'was-a-millionaire-until-last': 'Was a millionaire until last week',
  'has-million-followers-online': 'Has {n:1-3} million followers online',
  'knows-jokes-by-heart': 'Knows {n:300-900} jokes by heart',
  'can-cut-hair': 'Can cut hair',
  'can-navigate-by-the-stars': 'Can navigate by the stars',
  'former-cult-member': 'Former cult member',
  'has-a-hidden-stash-of-supplies': 'Has a hidden stash of supplies {n:5-50} km away',
  'can-raise-chickens-and-rabbits': 'Can raise chickens and rabbits',
  'can-milk-a-cow-and-make-cheese': 'Can milk a cow and make cheese',
  'built-a-house-with-their-own': 'Built a house with their own hands',
  'former-spy-or-so-they-claim': 'Former spy (or so they claim)',
  'learned-karate-from-online': 'Learned karate from online videos',
  'can-calm-any-animal-down': 'Can calm any animal down',
  'brilliant-negotiator': 'Brilliant negotiator',
  'can-juggle-knives': 'Can juggle {n:3-7} knives',
  'can-train-dogs': 'Can train dogs',
  'taught-children-to-read': 'Taught {n:2-40} children to read',
  'survived-weeks-alone-in-the': 'Survived {n:2-6} weeks alone in the forest',
  'volunteer-rescuer': 'Volunteer rescuer ({yrs:1-12})',
  'can-reprogram-any': 'Can reprogram any microcontroller',
  'plays-chess-blindfolded': 'Plays chess blindfolded',
  'can-find-water-with-a-dowsing': 'Can find water with a dowsing rod (allegedly)',
  'knows-cpr': 'Knows CPR',
  'can-set-broken-bones': 'Can set broken bones',
  'can-grow-penicillin-mold-and': 'Can grow penicillin mold (and hopes it works)',
  'needs-only-hours-of-sleep': 'Needs only {n:3-5} hours of sleep',
  'former-hostage-negotiator': 'Former hostage negotiator',
  'can-forge-any-signature-or': 'Can forge any signature or document',
  'can-build-a-radio-out-of-junk': 'Can build a radio out of junk',
  'can-butcher-and-preserve-meat': 'Can butcher and preserve meat',
  'can-tan-leather-and-sew-clothes': 'Can tan leather and sew clothes',
  'has-read-everything-about': 'Has read everything about emergency surgery (never tried it)',
  'can-recite-the-periodic-table': 'Can recite the periodic table',
  'former-professional-poker-player': 'Former professional poker player',
  'has-a-pilots-license-for-small': "Has a pilot's license for small planes",
  'can-weld-and-forge-metal': 'Can weld and forge metal',
  'knows-how-to-brew-beer': 'Knows how to brew beer',
  'knows-how-to-make-gunpowder': 'Knows how to make gunpowder',
  'can-make-anyone-laugh-in-any': 'Can make anyone laugh in any situation',
  'knows-how-to-chair-a-meeting-and': 'Knows how to chair a meeting and count votes',
  'regional-debate-champion': 'Regional debate champion',
  'reads-tarot-cards-and-people': 'Reads tarot cards, and people believe them',
  'can-make-clothes-out-of-anything': 'Can make clothes out of anything',
  'knows-traditional-herbal': 'Knows traditional herbal medicine',
  'plays-the-harmonica-loudly': 'Plays the harmonica, loudly',
  'can-identify-birds-by-their-song': 'Can identify {n:100-500} birds by their song',
  'parachute-instructor-jumps': 'Parachute instructor ({n:100-900} jumps)',
  'former-child-actor-still-gets': 'Former child actor (still gets recognized)',
  'knows-how-to-keep-bees': 'Knows how to keep bees',
  'can-hold-their-breath-for': 'Can hold their breath for {n:2-5} minutes',
};
