// English Personality cards: 80 entries.
//
// Today's English strings, verbatim, keyed by stable ids (reports/i18n-design.md §6.1–§6.2). The ids never change
// once published (B1): a reworded card keeps its id. The key order is the deck order, so reordering or inserting
// entries changes what a seed deals (the golden test in test/i18n-golden-content.test.js says so on purpose).
//
// Placeholders are drawn left to right when the card is dealt:
//   {n:a-b}    a whole number from a to b
//   {yrs:a-b}  "N years" ("1 year"), N from a to b
//   {sev}      a severity word from ./mods.js (mild / moderate / severe)
//   {x|y|z}    one of the options
// ../ru/ refers to them by position: {0} is the first placeholder, {1} the second (design §6.3).
export default {
  'honest-to-a-fault': 'Honest to a fault',
  'hot-tempered': 'Hot-tempered',
  'born-leader': 'Born leader',
  'coward': 'Coward',
  'incurable-optimist': 'Incurable optimist',
  'pathological-liar': 'Pathological liar',
  'kind-hearted': 'Kind-hearted',
  'lazy': 'Lazy',
  'paranoid': 'Paranoid',
  'workaholic': 'Workaholic',
  'gloomy-pessimist': 'Gloomy pessimist',
  'charismatic': 'Charismatic',
  'stubborn-as-a-mule': 'Stubborn as a mule',
  'know-it-all': 'Know-it-all',
  'calm-under-pressure': 'Calm under pressure',
  'greedy': 'Greedy',
  'generous': 'Generous',
  'jealous': 'Jealous',
  'hypocrite': 'Hypocrite',
  'natural-diplomat': 'Natural diplomat',
  'introvert': 'Introvert',
  'life-of-the-party': 'Life of the party',
  'perfectionist': 'Perfectionist',
  'clumsy': 'Clumsy',
  'forgetful': 'Forgetful',
  'gossip': 'Gossip',
  'fiercely-loyal': 'Fiercely loyal',
  'manipulative': 'Manipulative',
  'brave': 'Brave',
  'reckless': 'Reckless',
  'overly-cautious': 'Overly cautious',
  'always-cheerful': 'Always cheerful',
  'grumpy': 'Grumpy',
  'sarcastic': 'Sarcastic',
  'naive': 'Naive',
  'cynical': 'Cynical',
  'religious-zealot': 'Religious zealot',
  'neat-freak': 'Neat freak',
  'slob': 'Slob',
  'hoarder': 'Hoarder',
  'glutton': 'Glutton',
  'ascetic': 'Ascetic',
  'hopeless-romantic': 'Hopeless romantic',
  'incorrigible-flirt': 'Incorrigible flirt',
  'sore-loser': 'Sore loser',
  'ultra-competitive': 'Ultra-competitive',
  'team-player': 'Team player',
  'lone-wolf': 'Lone wolf',
  'holds-grudges-forever': 'Holds grudges forever',
  'forgives-everything': 'Forgives everything',
  'deeply-empathetic': 'Deeply empathetic',
  'cold-and-calculating': 'Cold and calculating',
  'turns-everything-into-a-drama': 'Turns everything into a drama',
  'impulsive': 'Impulsive',
  'endlessly-patient': 'Endlessly patient',
  'endlessly-curious': 'Endlessly curious',
  'superstitious': 'Superstitious',
  'believes-every-conspiracy-theory': 'Believes every conspiracy theory',
  'show-off': 'Show-off',
  'modest': 'Modest',
  'bossy': 'Bossy',
  'does-whatever-they-are-told': 'Does whatever they are told',
  'rebel': 'Rebel',
  'anxious': 'Anxious',
  'chatterbox': 'Chatterbox',
  'speaks-only-when-necessary': 'Speaks only when necessary',
  'night-owl': 'Night owl',
  'early-bird': 'Early bird',
  'kleptomaniac': 'Kleptomaniac',
  'easily-offended': 'Easily offended',
  'thick-skinned': 'Thick-skinned',
  'peacemaker': 'Peacemaker',
  'sneaky': 'Sneaky',
  'tells-long-boring-stories': 'Tells long, boring stories',
  'always-late': 'Always late',
  'hero-complex': 'Hero complex',
  'strict-pacifist': 'Strict pacifist',
  'tactless': 'Tactless',
  'exceedingly-polite': 'Exceedingly polite',
  'complains-constantly': 'Complains constantly',
};
